# Generated by Django 2.1.5 on 2019-09-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('property_type', models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('b', 'big')], max_length=20)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
